### ISSUE TITLE
`enableGrowth=false` does not disable the growth of the container

### ISSUE THREAD

**Issue by Eptis** [ef4/liquid-fire#298]
`{{liquid-outlet enableGrowth=false}}` still grows and shrinks the container in version `0.19`

**Comment by ef4** [comment]
This got fixed in the 0.20.x series at 69f251c5ff659e3128bf2ab8519db4ed5e18e30c, we need a backport.

**Comment by Eptis** [comment]
I'm still having this issue in 0.20.4. I'm now working arround it with `min-height: 100%` in a flex-container but without that the `liquid-container` still grows/shrinks
